[package]
name = "macros"
version = "0.1.0"
edition = "2021"
description = "Procedural macros for the par-reader crate"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0"
syn = { version = "2.0.101", features = ["full", "extra-traits"] }
darling = "0.20.11"
